name: Test

on:
  push:
    branches:
      - 'develop'


jobs:
  docker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: '15.x'

    steps:
    - uses: actions/checkout@v2
    - name: Node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - run: yarn test
